openapi: 3.0.0
info:
  title: Emptybox API Reference
  description: |
    This document provides API reference to Emptybox backend service.
  version: v0.0.1
paths:
  /stats:
    get:
      description: |
        Returns the number of all files that are stored in the system.
      responses:
        '200':
          description: Number of files
          content:
            application/json:
              schema:
                type: object
                properties:
                  fileCount:
                    type: integer
              examples:
                empty:
                  summary: The server is empty
                  value: {"fileCount": 0}
                elite:
                  summary: Elite number of files on server
                  value: {"fileCount": 1337}
  /upload:
    post:
      description: |
        Save the attached file
      requestBody:
        description: Descripting the file to be saved
        required: true
        content:
          multipart/form-data:
            schema:
              required:
               - type
              properties:
                type:
                  type: string
                  enum:
                   - file
                   - url
                file:
                  type: string
                  description: Required if type is "file"
                  format: binary
                url:
                  type: string
                  description: Required if type is "url"
      responses:
        '200':
          description: Successful message
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    description: Descriptive response
                  filename:
                    description: Saved filename
                    type: string
              examples:
                success:
                  summary: Message when file is saved successfully
                  value:
                    msg: Saved
                    filename: 2c4560f9-613d-43f4-b7e5-190a101959d3.png
        '400':
          description: Error responses message
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    description: Descriptive response
              examples:
                nofile:
                  summary: Message when no file is provided
                  value:
                    msg: Invalid Request
                notype:
                  summary: When type parameter is missing
                  value:
                    msg: Invalid Request
                error:
                  summary: Other errors
                  value: Error
